services:
  - type: web
    name: bus-tracking-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false